import 'package:flutter/material.dart';

class IconsHelper {
  // Access all categories
  static List<String> get categories => categorizedIcons.keys.toList();

  // Get icons for a specific category
  static List<String>? getIconsByCategory(String category) => categorizedIcons[category];

  static Map<String, List<String>> categorizedIcons = {
    'Transportation': [
      'agriculture', 'airport_shuttle', 'bike_scooter', 'directions_bike',
      'directions_boat', 'directions_car', 'emoji_transportation', 'flight',
      'local_airport', 'local_gas_station', 'local_shipping', 'local_taxi',
      'motorcycle', 'pedal_bike', 'snowmobile', 'taxi_alert', 'traffic',
      'train', 'tram', 'two_wheeler'
    ],
    'Food & Dining': [
      'bakery_dining', 'blender', 'fastfood', 'flatware', 'free_breakfast',
      'lunch_dining', 'restaurant', 'restaurant_menu', 'room_service',
      'set_meal', 'sports_bar', 'tapas', 'wine_bar'
    ],
    'Sports & Recreation': [
      'anchor', 'beach_access', 'downhill_skiing', 'festival', 'fitness_center',
      'hiking', 'hot_tub', 'ice_skating', 'kayaking', 'kitesurfing', 'pool',
      'rowing', 'sailing', 'self_improvement', 'skateboarding', 'sledding',
      'snowboarding', 'snowshoeing', 'sports', 'sports_baseball', 'sports_basketball',
      'sports_cricket', 'sports_esports', 'sports_football', 'sports_golf',
      'sports_handball', 'sports_hockey', 'sports_kabaddi', 'sports_motorsports',
      'sports_rugby', 'sports_soccer', 'sports_tennis', 'sports_volleyball',
      'surfing', 'theater_comedy'
    ],
    'Shopping & Commerce': [
      'local_grocery_store', 'local_mall', 'receipt', 'receipt_long',
      'sell', 'shopping_cart', 'store', 'storefront'
    ],
    'Work & Tech': [
      'adb', 'ad_units', 'architecture', 'biotech', 'build', 'engineering',
      'handyman', 'headphones', 'local_print_shop', 'mouse', 'precision_manufacturing',
      'science', 'sensors', 'settings_input_component', 'shutter_speed',
      'smart_toy', 'smartphone', 'straighten', 'tablet_mac', 'timer',
      'wifi_protected_setup', 'wifi_tethering', 'work', 'workspaces'
    ],
    'Nature & Weather': [
      'ac_unit', 'air', 'eco', 'filter_hdr', 'flash_on', 'flashlight_on',
      'grass', 'local_florist', 'storm', 'terrain', 'umbrella', 'waves',
      'wb_cloudy', 'wb_incandescent', 'wb_shade', 'wb_sunny', 'whatshot'
    ],
    'People & Health': [
      'accessibility_new', 'accessible', 'accessible_forward', 'bathtub',
      'child_care', 'child_friendly', 'family_restroom', 'favorite',
      'pregnant_woman', 'smoke_free', 'smoking_rooms', 'stroller', 'support', 'support_agent'
    ],
    'Social & Feelings': [
      'sentiment_dissatisfied', 'sentiment_neutral', 'sentiment_satisfied',
      'sentiment_satisfied_alt', 'sentiment_very_dissatisfied',
      'sentiment_very_satisfied', 'tag_faces'
    ],
    'Places & Misc': [
      'audiotrack', 'flag', 'follow_the_signs', 'grade', 'hotel',
      'local_fire_department', 'local_hotel', 'local_see', 'school',
      'security', 'theaters', 'tour', 'toys', 'track_changes'
    ],
  };

  static Map<String, IconData> iconMap = {
    'ac_unit': Icons.ac_unit,
    'accessibility_new': Icons.accessibility_new,
    'accessible': Icons.accessible,
    'accessible_forward': Icons.accessible_forward,
    'ad_units': Icons.ad_units,
    'adb': Icons.adb,
    'agriculture': Icons.agriculture,
    'air': Icons.air,
    'airport_shuttle': Icons.airport_shuttle,
    'anchor': Icons.anchor,
    'architecture': Icons.architecture,
    'audiotrack': Icons.audiotrack,
    'bakery_dining': Icons.bakery_dining,
    'bathtub': Icons.bathtub,
    'beach_access': Icons.beach_access,
    'bike_scooter': Icons.bike_scooter,
    'biotech': Icons.biotech,
    'blender': Icons.blender,
    'build': Icons.build,
    'child_care': Icons.child_care,
    'child_friendly': Icons.child_friendly,
    'directions_bike': Icons.directions_bike,
    'directions_boat': Icons.directions_boat,
    'directions_car': Icons.directions_car,
    'downhill_skiing': Icons.downhill_skiing,
    'eco': Icons.eco,
    'emoji_transportation': Icons.emoji_transportation,
    'engineering': Icons.engineering,
    'family_restroom': Icons.family_restroom,
    'fastfood': Icons.fastfood,
    'favorite': Icons.favorite,
    'festival': Icons.festival,
    'filter_hdr': Icons.filter_hdr,
    'fitness_center': Icons.fitness_center,
    'flag': Icons.flag,
    'flash_on': Icons.flash_on,
    'flashlight_on': Icons.flashlight_on,
    'flatware': Icons.flatware,
    'flight': Icons.flight,
    'follow_the_signs': Icons.follow_the_signs,
    'free_breakfast': Icons.free_breakfast,
    'grade': Icons.grade,
    'grass': Icons.grass,
    'handyman': Icons.handyman,
    'headphones': Icons.headphones,
    'hiking': Icons.hiking,
    'hot_tub': Icons.hot_tub,
    'hotel': Icons.hotel,
    'ice_skating': Icons.ice_skating,
    'kayaking': Icons.kayaking,
    'kitesurfing': Icons.kitesurfing,
    'local_airport': Icons.local_airport,
    'local_fire_department': Icons.local_fire_department,
    'local_florist': Icons.local_florist,
    'local_gas_station': Icons.local_gas_station,
    'local_grocery_store': Icons.local_grocery_store,
    'local_hotel': Icons.local_hotel,
    'local_print_shop': Icons.local_print_shop,
    'local_see': Icons.local_see,
    'local_shipping': Icons.local_shipping,
    'local_taxi': Icons.local_taxi,
    'lunch_dining': Icons.lunch_dining,
    'motorcycle': Icons.motorcycle,
    'mouse': Icons.mouse,
    'pedal_bike': Icons.pedal_bike,
    'pool': Icons.pool,
    'precision_manufacturing': Icons.precision_manufacturing,
    'pregnant_woman': Icons.pregnant_woman,
    'restaurant': Icons.restaurant,
    'restaurant_menu': Icons.restaurant_menu,
    'room_service': Icons.room_service,
    'rowing': Icons.rowing,
    'sailing': Icons.sailing,
    'school': Icons.school,
    'science': Icons.science,
    'security': Icons.security,
    'self_improvement': Icons.self_improvement,
    'sell': Icons.sell,
    'sensors': Icons.sensors,
    'sentiment_dissatisfied': Icons.sentiment_dissatisfied,
    'sentiment_neutral': Icons.sentiment_neutral,
    'sentiment_satisfied': Icons.sentiment_satisfied,
    'sentiment_satisfied_alt': Icons.sentiment_satisfied_alt,
    'sentiment_very_dissatisfied': Icons.sentiment_very_dissatisfied,
    'sentiment_very_satisfied': Icons.sentiment_very_satisfied,
    'set_meal': Icons.set_meal,
    'settings_input_component': Icons.settings_input_component,
    'shopping_cart': Icons.shopping_cart,
    'shutter_speed': Icons.shutter_speed,
    'skateboarding': Icons.skateboarding,
    'sledding': Icons.sledding,
    'smart_toy': Icons.smart_toy,
    'smartphone': Icons.smartphone,
    'smoke_free': Icons.smoke_free,
    'smoking_rooms': Icons.smoking_rooms,
    'snowboarding': Icons.snowboarding,
    'snowmobile': Icons.snowmobile,
    'snowshoeing': Icons.snowshoeing,
    'speed': Icons.speed,
    'sports': Icons.sports,
    'sports_bar': Icons.sports_bar,
    'sports_baseball': Icons.sports_baseball,
    'sports_basketball': Icons.sports_basketball,
    'sports_cricket': Icons.sports_cricket,
    'sports_esports': Icons.sports_esports,
    'sports_football': Icons.sports_football,
    'sports_golf': Icons.sports_golf,
    'sports_handball': Icons.sports_handball,
    'sports_hockey': Icons.sports_hockey,
    'sports_kabaddi': Icons.sports_kabaddi,
    'sports_motorsports': Icons.sports_motorsports,
    'sports_rugby': Icons.sports_rugby,
    'sports_soccer': Icons.sports_soccer,
    'sports_tennis': Icons.sports_tennis,
    'sports_volleyball': Icons.sports_volleyball,
    'store': Icons.store,
    'storefront': Icons.storefront,
    'storm': Icons.storm,
    'straighten': Icons.straighten,
    'stroller': Icons.stroller,
    'support': Icons.support,
    'support_agent': Icons.support_agent,
    'surfing': Icons.surfing,
    'tablet_mac': Icons.tablet_mac,
    'tag_faces': Icons.tag_faces,
    'tapas': Icons.tapas,
    'taxi_alert': Icons.taxi_alert,
    'terrain': Icons.terrain,
    'theater_comedy': Icons.theater_comedy,
    'theaters': Icons.theaters,
    'timer': Icons.timer,
    'tour': Icons.tour,
    'toys': Icons.toys,
    'track_changes': Icons.track_changes,
    'traffic': Icons.traffic,
    'train': Icons.train,
    'tram': Icons.tram,
    'two_wheeler': Icons.two_wheeler,
    'umbrella': Icons.umbrella,
    'waves': Icons.waves,
    'wb_cloudy': Icons.wb_cloudy,
    'wb_incandescent': Icons.wb_incandescent,
    'wb_shade': Icons.wb_shade,
    'wb_sunny': Icons.wb_sunny,
    'whatshot': Icons.whatshot,
    'wifi_protected_setup': Icons.wifi_protected_setup,
    'wifi_tethering': Icons.wifi_tethering,
    'wine_bar': Icons.wine_bar,
    'work': Icons.work,
    'workspaces': Icons.workspaces,
    'local_mall': Icons.local_mall,
    'receipt': Icons.receipt,
    'receipt_long': Icons.receipt_long,
  };

  static IconData? getIcon(String key) => iconMap[key];
}